### ISSUE TITLE
fix condx

### ISSUE THREAD

**Issue by galengold** [young-amateurs-rc/qrmbot-discord#11]
> I simply have requests download the image at the url, save it to disk, and pass the file handle over to discord.py and tell it to upload
> I could probably use a StringIO or something to not have to write to disk but eh
> Yeah I wanted to reduce load on the server because the info likely won't change over the course of 20 minutes so I just have it cache it for 2h

**Comment by ntoskrnl4** [comment]
> [text in original post]

🤔 this sounds familiar
