### ISSUE TITLE
Add greyline propagation map feature

### ISSUE THREAD

**Issue by bruceyang1998** [young-amateurs-rc/qrmbot-discord#17]
Possible source: http://www.fourmilab.ch/cgi-bin/uncgi/Earth?img=NOAAtopo.evif&imgsize=320&dynimg=y&opt=-p&lat=&lon=&alt=&tle=&date=0&utc=&jd=

**Comment by bruceyang1998** [comment]
MUF map: http://www.spacew.com/www/realtime.gif
Potentially more useful, but the SSN is incorrect.

**Comment by galengold** [comment]
#19
