### ISSUE TITLE
Pic for figures aren't showing up

### ISSUE THREAD

**Issue by LFGSaito** [young-amateurs-rc/qrmbot-discord#4]
Let see if I can fix this.

**Comment by galengold** [comment]
@LFGSaito where did you get the question pool json files from again?

**Comment by galengold** [comment]
can fix with https://discordpy.readthedocs.io/ja/rewrite/api.html#discord.Embed.set_image

**Comment by galengold** [comment]
Questions come from here: https://github.com/shortword/honey_glazed

looks like there isn't an easy way to determine which image to show from the JSON. Submitted an issue on the question repo.

**Comment by galengold** [comment]
fixed in b7e0181
